# -*- coding: utf-8 -*-
"""trabalhando_com_list_comprehension.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TjAoOu64p9n_6W7kKydzLDbBKS-T4aW8

## Estudos Gerais

### Trabalhando com list comprehension, filter, map e lambda functions

Autor: **Jonatan Nascimento**
"""

a = [1,2,3,4,5]
b = [ i * 2 for i in a] |# list comprehension
print(b)

c = list(filter(lambda x: x<5, b)) # melhor que dar colchetes!
print(c)

d = list(map(lambda x: pow(x,3), a)) # usando a função map
print(d)

